export const BRAND_TOOLS = [
  {
    id: 'brand-kit',
    number: '01',
    category: 'Brand Foundation',
    title: 'Brand Kit',
    href: '/brand-tools/brand-kit',
    tagline: 'Unified visual identity manager & guideline generator',
    description: 'Establish, store, and deploy your complete brand identity system. Powers all creative tools, exports production CSS variables, and compiles multi-page Brand Guidelines PDFs.',
    icon: 'palette-book',
    related: ['color-palette', 'business-card', 'email-signature', 'qr-code'],
  },
  {
    id: 'color-palette',
    number: '02',
    category: 'Brand Foundation',
    title: 'Color Palette',
    href: '/brand-tools/color-palette',
    tagline: 'Client-side image color clustering & extraction',
    description: 'Upload logos or photography to extract dominant, harmonious color systems instantly. Inspect HEX, RGB, HSL, and CMYK tokens with one-click Brand Kit sync.',
    icon: 'eyedropper',
    related: ['brand-kit', 'gradient', 'color-contrast'],
  },
  {
    id: 'gradient',
    number: '03',
    category: 'Brand Foundation',
    title: 'Gradient Generator',
    href: '/brand-tools/gradient',
    tagline: 'Multi-stop linear and radial gradient design',
    description: 'Design mathematically smooth linear and radial gradients using your Brand Kit colors. Copy standard CSS rules or download high-resolution 1080p PNG wallpapers.',
    icon: 'gradient',
    related: ['brand-kit', 'color-palette', 'color-contrast'],
  },
  {
    id: 'color-contrast',
    number: '04',
    category: 'Brand Foundation',
    title: 'Color Contrast & Shades',
    href: '/brand-tools/color-contrast',
    tagline: 'WCAG 2.1 AA/AAA compliance & tonal scale generator',
    description: 'Audit typography and interface accessibility ratios in real time. Generate systematically calibrated 10-step tint and shade scales for digital design systems.',
    icon: 'contrast',
    related: ['brand-kit', 'color-palette', 'gradient'],
  },
  {
    id: 'business-card',
    number: '05',
    category: 'Branded Assets',
    title: 'Business Card',
    href: '/brand-tools/business-card',
    tagline: 'Standard 3.5×2 inch print-ready stationery with vCard QR',
    description: 'Generate commercial print-ready business cards styled with your brand logo, colors, and typography. Includes dynamic vCard QR code integration and 300 DPI PDF export.',
    icon: 'credit-card',
    related: ['brand-kit', 'qr-code', 'email-signature'],
  },
  {
    id: 'email-signature',
    number: '06',
    category: 'Branded Assets',
    title: 'Email Signature',
    href: '/brand-tools/email-signature',
    tagline: 'Responsive HTML signatures for Gmail, Outlook & Apple Mail',
    description: 'Generate email-client-compatible HTML table signatures formatted with clean inline CSS. Auto-fills your brand assets and provides one-click rich formatting copy.',
    icon: 'mail',
    related: ['brand-kit', 'business-card', 'letterhead'],
  },
  {
    id: 'letterhead',
    number: '07',
    category: 'Branded Assets',
    title: 'Letterhead',
    href: '/brand-tools/letterhead',
    tagline: 'Standardized A4 corporate stationery & vector PDF export',
    description: 'Generate official A4 business correspondence with your vector logo, header styles, and typographic hierarchy. Includes live editing, print preview, and vector PDF download.',
    icon: 'file-text',
    related: ['brand-kit', 'email-signature', 'business-card'],
  },
  {
    id: 'qr-code',
    number: '08',
    category: 'Branded Assets',
    title: 'QR Code Generator',
    href: '/brand-tools/qr-code',
    tagline: 'Custom branded QR codes with logo embedding & SVG export',
    description: 'Create customized, high-reliability QR codes for URLs, vCards, WiFi networks, and contact info. Apply brand colors, embed your center logo, and export scalable SVGs or high-res PNGs.',
    icon: 'qr-code',
    related: ['brand-kit', 'business-card', 'color-palette'],
  },
];
