const projects = [
  {
    id: 'video-strategy',
    title: 'Video Content Strategy',
    img: '/video-strategy/video-strategy.webp',
    link: '/projects/video-strategy',
    date: '2023',
    liveLink: undefined,
    company: 'YouTube / Socials',
    primary: '#2D2D2D',
    accentColor: '#FCFBF7',
    secondary: '#F2EEE7',
    fillColor: '#F2F3F4',
    menuColor: 'gold',
    menuFontColor: '#2D2D2D',
    fluidColor: '#0028FF',
    images: [
      {
        src: '/video-strategy/video.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/video-strategy/7.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/video-strategy/6.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/video-strategy/video2.mp4',
        tag: 'video',
        isRight: false,
      },
      {
        src: '/video-strategy/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/video-strategy/5.webp',
        tag: 'small',
        isRight: false,
      },
      {
        src: '/video-strategy/8.webp',
        tag: 'small',
        isRight: true,
      },
      {
        src: '/video-strategy/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/video-strategy/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'A technology solutions venture focused on digital innovation, building scalable systems and tools for modern businesses.',
      'Working on revenue growth strategies, product development, and leading cross-functional teams to deliver impactful results.',
      'Focused on leveraging cutting-edge technologies to create solutions that solve real-world business challenges.',
    ],
  },
  {
    id: 'content-creation',
    title: 'Content Creation',
    img: '/content-creation/content-creation.webp',
    link: '/projects/content-creation',
    date: '2024',
    company: 'Digital Media',
    liveLink: undefined,
    primary: '#263745',
    accentColor: '#f0f4f1',
    secondary: '#F3F5F7',
    fillColor: '#E0DFFC',
    menuColor: '#5C58EB',
    menuFontColor: '#f0f4f1',
    fluidColor: '#A3A714',
    images: [
      {
        src: '/content-creation/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/content-creation/2.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/content-creation/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/content-creation/4.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/content-creation/5.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/content-creation/6.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/content-creation/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/content-creation/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/content-creation/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/content-creation/10.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/content-creation/11.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'A strategic planning and event solutions company providing end-to-end business planning, event management, and consulting services.',
      'Handled business strategy, operations, and company growth while ensuring client satisfaction across diverse project portfolios.',
      'Built processes and frameworks that enabled scalable service delivery and consistent quality outcomes.',
    ],
  },
  {
    id: 'digital-campaigns',
    title: 'Digital Campaigns & Operations',
    img: '/digital-campaigns/digital-campaigns.webp',
    link: '/projects/digital-campaigns',
    date: '2024',
    company: 'Digital Campaigns',
    liveLink: undefined,
    primary: '#000000',
    accentColor: '#f0f4f1',
    secondary: '#FAFAFA',
    fillColor: '#f2f2f2',
    menuColor: '#FFD54F',
    menuFontColor: '#000000',
    fluidColor: '#002AB0',
    images: [
      {
        src: '/digital-campaigns/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/digital-campaigns/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/digital-campaigns/3.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/digital-campaigns/4.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/digital-campaigns/5.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/digital-campaigns/6.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/digital-campaigns/7.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/digital-campaigns/8.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/digital-campaigns/9.webp',
        tag: 'medium',
        isRight: false,
      },
      {
        src: '/digital-campaigns/10.webp',
        tag: 'medium',
        isRight: false,
      },
    ],
    desc: [
      'Led advertising operations, marketing campaigns, and brand strategy initiatives for clients across multiple industries.',
      'Developed and executed comprehensive marketing strategies that drove measurable results in brand awareness and customer acquisition.',
      'Managed creative teams and client relationships while scaling business operations and expanding service offerings.',
      'Built a reputation for delivering innovative advertising solutions that combined digital marketing with traditional media approaches.',
    ],
  },
  {
    id: 'brand-storytelling',
    title: 'Brand Storytelling',
    img: '/brand-storytelling/brand-storytelling.webp',
    link: '/projects/brand-storytelling',
    date: '2022',
    company: 'Cure Vibes',
    liveLink: undefined,
    primary: '#0e0063',
    accentColor: '#f0f4f1',
    secondary: '#fbfbfc',
    fillColor: '#e1e1f9',
    menuColor: '#170053',
    menuFontColor: '#f0f4f1',
    fluidColor: '#E8FFC8',
    images: [
      {
        src: '/brand-storytelling/video.mp4',
        tag: 'video',
        isRight: true,
      },
      {
        src: '/brand-storytelling/1.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/brand-storytelling/2.webp',
        tag: 'big',
        isRight: false,
      },
      {
        src: '/brand-storytelling/3.webp',
        tag: 'big',
        isRight: false,
      },
    ],
    desc: [
      'A healthcare initiative co-founded in Kathmandu, Nepal, focused on healthcare management and compliance services.',
      'Developed healthcare service delivery frameworks and ensured regulatory compliance across operations.',
      'Built partnerships with healthcare providers and created systems for efficient patient management.',
      'Focused on making quality healthcare services more accessible and well-managed in the local market.',
    ],
  },
];
export default projects;
